// Code generated by Wire protocol buffer compiler, do not edit.
// Source: screen.v1.ComponentV1 in screen.proto
package screen.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class ComponentV1(
  @field:WireField(
    tag = 1,
    adapter = "screen.v1.ButtonV1#ADAPTER",
    oneofName = "component",
    schemaIndex = 0,
  )
  public val button: ButtonV1? = null,
  @field:WireField(
    tag = 2,
    adapter = "screen.v1.CardV1#ADAPTER",
    oneofName = "component",
    schemaIndex = 1,
  )
  public val card: CardV1? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ComponentV1, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(button, card) <= 1) {
      "At most one of button, card may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ComponentV1) return false
    if (unknownFields != other.unknownFields) return false
    if (button != other.button) return false
    if (card != other.card) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (button?.hashCode() ?: 0)
      result = result * 37 + (card?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (button != null) result += """button=$button"""
    if (card != null) result += """card=$card"""
    return result.joinToString(prefix = "ComponentV1{", separator = ", ", postfix = "}")
  }

  public fun copy(
    button: ButtonV1? = this.button,
    card: CardV1? = this.card,
    unknownFields: ByteString = this.unknownFields,
  ): ComponentV1 = ComponentV1(button, card, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ComponentV1> = object : ProtoAdapter<ComponentV1>(
      FieldEncoding.LENGTH_DELIMITED, 
      ComponentV1::class, 
      "type.googleapis.com/screen.v1.ComponentV1", 
      PROTO_3, 
      null, 
      "screen.proto"
    ) {
      override fun encodedSize(`value`: ComponentV1): Int {
        var size = value.unknownFields.size
        size += ButtonV1.ADAPTER.encodedSizeWithTag(1, value.button)
        size += CardV1.ADAPTER.encodedSizeWithTag(2, value.card)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ComponentV1) {
        ButtonV1.ADAPTER.encodeWithTag(writer, 1, value.button)
        CardV1.ADAPTER.encodeWithTag(writer, 2, value.card)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ComponentV1) {
        writer.writeBytes(value.unknownFields)
        CardV1.ADAPTER.encodeWithTag(writer, 2, value.card)
        ButtonV1.ADAPTER.encodeWithTag(writer, 1, value.button)
      }

      override fun decode(reader: ProtoReader): ComponentV1 {
        var button: ButtonV1? = null
        var card: CardV1? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> button = ButtonV1.ADAPTER.decode(reader)
            2 -> card = CardV1.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ComponentV1(
          button = button,
          card = card,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ComponentV1): ComponentV1 = value.copy(
        button = value.button?.let(ButtonV1.ADAPTER::redact),
        card = value.card?.let(CardV1.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
