// Code generated by Wire protocol buffer compiler, do not edit.
// Source: screen.v1.GetScreenRequest in screen.proto
package screen.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class GetScreenRequest(
  /**
   * Screen ID must always be present
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "screenId",
    schemaIndex = 0,
  )
  public val screen_id: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<GetScreenRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is GetScreenRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (screen_id != other.screen_id) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + screen_id.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """screen_id=${sanitize(screen_id)}"""
    return result.joinToString(prefix = "GetScreenRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(screen_id: String = this.screen_id, unknownFields: ByteString =
      this.unknownFields): GetScreenRequest = GetScreenRequest(screen_id, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<GetScreenRequest> = object : ProtoAdapter<GetScreenRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      GetScreenRequest::class, 
      "type.googleapis.com/screen.v1.GetScreenRequest", 
      PROTO_3, 
      null, 
      "screen.proto"
    ) {
      override fun encodedSize(`value`: GetScreenRequest): Int {
        var size = value.unknownFields.size
        if (value.screen_id != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1,
            value.screen_id)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: GetScreenRequest) {
        if (value.screen_id != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.screen_id)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: GetScreenRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.screen_id != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.screen_id)
      }

      override fun decode(reader: ProtoReader): GetScreenRequest {
        var screen_id: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> screen_id = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return GetScreenRequest(
          screen_id = screen_id,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: GetScreenRequest): GetScreenRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
