// Code generated by Wire protocol buffer compiler, do not edit.
// Source: screen.v1.ScreenService in screen.proto
package screen.v1

import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcClient
import com.squareup.wire.GrpcMethod
import com.squareup.wire.ProtoAdapter
import kotlin.Unit

public class GrpcScreenServiceClient(
  private val client: GrpcClient,
) : ScreenServiceClient {
  override fun ErrorTester(): GrpcCall<ErrorTesterRequest, Unit> = client.newCall(GrpcMethod(
      path = "/screen.v1.ScreenService/ErrorTester",
      requestAdapter = ErrorTesterRequest.ADAPTER,
      responseAdapter = ProtoAdapter.EMPTY
  ))

  /**
   * Returns a SDUI screen.
   */
  override fun GetScreen(): GrpcCall<GetScreenRequest, GetScreenResponse> =
      client.newCall(GrpcMethod(
      path = "/screen.v1.ScreenService/GetScreen",
      requestAdapter = GetScreenRequest.ADAPTER,
      responseAdapter = GetScreenResponse.ADAPTER
  ))
}
