// Code generated by Wire protocol buffer compiler, do not edit.
// Source: screen.v1.ScreenService in screen.proto
package screen.v1

import com.squareup.wire.GrpcCall
import com.squareup.wire.Service
import kotlin.Unit

public interface ScreenServiceClient : Service {
  public fun ErrorTester(): GrpcCall<ErrorTesterRequest, Unit>

  /**
   * Returns a SDUI screen.
   */
  public fun GetScreen(): GrpcCall<GetScreenRequest, GetScreenResponse>
}
