// Code generated by Wire protocol buffer compiler, do not edit.
// Source: screen.v1.style in screen.proto
package screen.v1

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int

/**
 * Style enum for the button
 */
public enum class style(
  override val `value`: Int,
) : WireEnum {
  PRIMARY(0),
  SECONDARY(1),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<style> = object : EnumAdapter<style>(
      style::class, 
      PROTO_3, 
      style.PRIMARY
    ) {
      override fun fromValue(`value`: Int): style? = style.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): style? = when (value) {
      0 -> PRIMARY
      1 -> SECONDARY
      else -> null
    }
  }
}
