// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: screen/v1/screen.proto
//
package screen.v1

import com.connectrpc.Headers
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.ResponseMessage
import com.google.protobuf.Empty

public class ScreenServiceClient(
  private val client: ProtocolClientInterface,
) : ScreenServiceClientInterface {
  override suspend fun errorTester(request: ErrorTesterRequest, headers: Headers):
      ResponseMessage<Empty> = client.unary(
    request,
    headers,
    MethodSpec(
    "screen.v1.ScreenService/ErrorTester",
      ErrorTesterRequest::class,
      com.google.protobuf.Empty::class,
    ),
  )


  /**
   *  Returns a SDUI screen.
   */
  override suspend fun getScreen(request: GetScreenRequest, headers: Headers):
      ResponseMessage<GetScreenResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "screen.v1.ScreenService/GetScreen",
      GetScreenRequest::class,
      GetScreenResponse::class,
    ),
  )

}
