// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: screen/v1/screen.proto
//
package screen.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage
import com.google.protobuf.Empty

public interface ScreenServiceClientInterface {
  public suspend fun errorTester(request: ErrorTesterRequest, headers: Headers = emptyMap()):
      ResponseMessage<Empty>

  /**
   *  Returns a SDUI screen.
   */
  public suspend fun getScreen(request: GetScreenRequest, headers: Headers = emptyMap()):
      ResponseMessage<GetScreenResponse>
}
